[package]
name = "rust_cli_app"
version = "0.1.0"
authors = ["Rafael Augusto da Silva Coelho"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
